name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: |
          pip install -U pip
          pip install yamllint ansible-lint
      - name: Check by yamllint
        run: |
          yamllint .
      - name: Check by ansible-lint
        run: |
          ansible-lint .
