name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        shell:
          - bash
          - zsh
          - fish
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install shell and ansible (ubuntu)
        if: startsWith(runner.os, 'Linux')
        run: |
          if type ${{ matrix.shell }} 2>&1 > /dev/null; then
            sudo apt update
            sudo apt install -y --no-install-recommends ${{ matrix.shell }}
          fi
          sudo apt install -y --no-install-recommends ansible
      - name: Install shell (macOS)
        if: startsWith(runner.os, 'macOS')
        run: |
          if type ${{ matrix.shell }} 2>&1 > /dev/null; then
            brew install ${{ matrix.shell }}
          fi
          brew install ansible
      - name: Change default login shell
        run: |
          sudo chsh -s $(which ${{ matrix.shell }})
      - name: Run test playbook
        run: |
          cd tests && ansible-playbook -i inventory -e asdf_default_shell=$(which ${{ matrix.shell }}) test.yml
