name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        shell:
          - bash
          - zsh
          - fish
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install ansible
        run: |
          pip install -U pip
          pip install ansible
      - name: Install shell (ubuntu)
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo apt update
          sudo apt install ${{ matrix.shell }}
      - name: Install shell (macOS)
        if: startsWith(runner.os, 'macOS')
        run: |
          if [ ${{ matrix.shell }} != "bash" ]; then
            brew install ${{ matrix.shell }}
          fi
      - name: Change default login shell
        run: |
          sudo chsh -s $(which ${{ matrix.shell }})
      - name: Run test playbook
        run: |
          cd tests && ansible-playbook -i inventory -e asdf_default_shell=$(which ${{ matrix.shell }}) test.yml
      - name: Check installed plugins (bash,zsh)
        if: ${{ matrix.shell != 'fish' }}
        run: |
          cd tests && . init_asdf.sh
          asdf --version
          asdf list golang
          asdf shell golang 1.15.13
          go version
          asdf list terraform
          asdf shell terraform 0.15.5
          terraform version
      - name: Check installed plugins (fish)
        if: ${{ matrix.shell == 'fish' }}
        run: |
          cd tests && source init_asdf.fish
          asdf --version
          asdf list golang
          asdf shell golang 1.15.13
          go version
          asdf list terraform
          asdf shell terraform 0.15.5
          terraform version
